export const COM_SHOW_SIDE_BAR = 'COM_SHOW_SIDE_BAR'  // 侧边栏
export const COM_SAVE_SEARCH_HISTORY = 'COM_SAVE_SEARCH_HISTORY' // 保存搜索历史
export const COM_DELETE_SEARCH_HISTORY = 'COM_DELETE_SEARCH_HISTORY'//删除搜索历史
export const COM_CLEER_SEARCH_HISTORY = 'COM_CLEER_SEARCH_HISTORY'
export const SET_PLAYLIST = 'SET_PLAYLIST'//设置播放列表
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'//设置播放音乐的索引